### ISSUE TITLE
why [eq. (8) in paper] is not the same with the code.

### ISSUE THREAD

**Issue by Woodpecker0** [hku-mars/ROG-Map#11]
In function globalIndexToLocalIndex(), the normalize step seems not the same with eq.(8) in paper. Before your code release, I try to implement rog_map, and my code is

template<typename PointT, typename ContainT> 
    inline Eigen::Vector3i RogMapContainer<PointT, ContainT>::normalize(const Eigen::Vector3i &t)
    { 
        Eigen::Vector3i l = t;
        for (int i = 0; i < 3; i++)
        {
            if (t[i] > s_half[i])
            {
                l[i] = t[i] - (s_half[i] + 1); // 论文似乎有错，论文是 t[i] - s_half[i]
            }
            else if (t[i] >= -s_half[i] && t[i] <= s_half[i])
            {
                l[i] = t[i] + s_half[i];
            }
            else if (t[i] < -s_half[i])
            {
                l[i] = t[i] + 3 * s_half[i] + 1; // 论文似乎有错，论文是 t[i] + 3*s_half[i]
            }
        } 
        return l;
}

Both work fine, but are they the same ? will it make any difference at the next slide reset step ?

**Comment by RENyunfan** [comment]
Thank you for carefully reviewing the paper and the code. Regarding your comment on the code: yes, the paper does contain some typos, but your code is correct. 

The normalization step in globalIndexToLocalIndex() slightly differs from equation (8) because the term s = （floor(s/2) * 2 + 1) is further added in getLocalIndexHash, which is mathematically equivalent. 

Similarly, the normalization in the map sliding function is analogous to equation (8), but in a more generalized form. The output of the function should be consistent with the expected result.

**Comment by Woodpecker0** [comment]
Thank you, I did not notice the difference in getLocalIndexHash().
