### ISSUE TITLE
How to adapt to dynamic scenes

### ISSUE THREAD

**Issue by kanavinnn** [hku-mars/ROG-Map#9]
Rog-map is a very great work.Thank you very much for openning source.I want to ask if this rog-map is only for local mapping of static scenes? When I keep the lidar stationary in a real-life scenario and people move around, the occupied voxels cannot be cleared, resulting in artifacts similar to those. Do you know how to solve this problem

**Comment by RENyunfan** [comment]
I am sorry that I'm currently traveling abroad for IROS 2024. I'll provide a more detailed example when I return home. In the meantime, you can try adjusting the probability update parameters in the diagram to better handle dynamic objects.

<img width="644" alt="image" src="https://github.com/user-attachments/assets/a43dfaed-c3c7-4b11-b46f-a0f9d005accc">

A suggested direction is to decrease the p_miss to reduce the artifacts left by the moving objects.

**Comment by kanavinnn** [comment]
Thanks for your reply. I just try to decrease the p_miss but it still have some voxel cannot be cleared and impact on planning.  When I play a wall behind the moving object, this issue is be sovled.I'm wondering if these voxels were not facilitated during the raycasting process due to some cloudpoints did not return.

**Comment by RENyunfan** [comment]
> Thanks for your reply. I just try to decrease the p_miss but it still have some voxel cannot be cleared and impact on planning. When I play a wall behind the moving object, this issue is be sovled.I'm wondering if these voxels were not facilitated during the raycasting process due to some cloudpoints did not return.

You're absolutely right. This is a common issue in LiDAR-based navigation because most LiDAR sensors cannot detect points at infinite distances (i.e., areas where there is no return signal). However, voxels occupied by dynamic objects can only be cleared when the laser beam hits the background.

Another approach is to create a depth image based on LiDAR's field of view, treating all pixels that weren't hit as having infinite depth (for example, assigning a large depth value, like 999 meters) and feeding this into the ROG-Map. However, this method also has its drawbacks.

Alternatively, you can try [M-detector](https://github.com/hku-mars/M-detector) from our lab to distinguish dynamic points and modify ROG-Map to deal with dynamic objects.

Personally, I haven't found a perfect solution yet, so if you have any suggestions or better alternatives, I’d greatly appreciate your input.

**Comment by RENyunfan** [comment]
I will close this issue and if you have any further questions, feel free to reopen it.

**Comment by kanavinnn** [comment]
I once try  the method of range-image similar to your approach, but i set the maximum range to a finite value.However it still have some questions. Our work focuses on engineering applications，so if some occupied voxel can't be cleared, the planning often fails. My solution is mapping for frame to frame, Initializing to set all voxels to free, If the point cloud falls into a voxel, set that voxel as occupied.The consequence is that we can't calculate the unknown space, and we can only plan in free space.

**Comment by kanavinnn** [comment]
I once try the method of range-image similar to your approach, but i set the maximum range to a finite value.However it still have some questions. Our work focuses on engineering applications，so if some occupied voxel can't be cleared, the planning often fails. My solution is mapping for frame to frame , Initializing to set all voxels to free  not using raycasting, If the point cloud falls into a voxel, set that voxel as occupied.The consequence is that we can't calculate the unknown space, and we can only plan in free space.
